//@BEGIN_IMG_imgS@
#include "wifi_on.c"
#include "plug_connected_unlocked.c"
#include "btn_start.c"
#include "plug_disconnected.c"
#include "nfc_off.c"
#include "ethernet_on.c"
#include "wifi_off.c"
#include "btn_stop.c"
#include "plug_error.c"
#include "calendar3.c"
#include "plug_connected_locked.c"
#include "ethernet_off.c"
#include "info_circle_fill.c"
#include "nfc_on.c"
#include "lightning_charge.c"
#include "tux_evsex40.c"
#include "stopwatch.c"
#include "battery_charge_on.c"
#include "reception_on.c"
#include "clock.c"
#include "plug_unknow.c"
#include "tux_evsex150.c"
#include "reception_off.c"
#include "translate.c"
#include "battery_charge_off.c"
//@END_IMG_imgS@